-- docker-compose.yml
 
version: '3.1'
 
services:
  mysql-master:
    image: mysql:5.7
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    volumes:
      - ./master-data:/var/lib/mysql
      - ./master-init:/docker-entrypoint-initdb.d
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --server-id=1 --log-bin=mysql-bin --binlog-ignore-db=mysql
 
  mysql-slave:
    image: mysql:5.7
    container_name: mysql-slave
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    ports:
      - "3308:3306"
    volumes:
      - ./slave-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --server-id=2 --relay-log=mysql-relay-bin --log-bin=mysql-bin --read-only=1
